### ISSUE TITLE
where is the "dataset_process.py"

### ISSUE THREAD

**Issue by euminds** [helblazer811/RefSAM#2]
As the title, I didn't find dataset_process.py to handle the refcoco !
[1680858533476](https://user-images.githubusercontent.com/46481864/230583739-3bb20cd0-fda0-4cf3-bdf2-46d18fab8279.jpg)
![1680858583027](https://user-images.githubusercontent.com/46481864/230583752-eccb840e-e1c1-4c4e-9c9c-73aa0f5e8567.jpg)

**Comment by Lyan-ing** [comment]
> As the title, I didn't find dataset_process.py to handle the refcoco ! [1680858533476](https://user-images.githubusercontent.com/46481864/230583739-3bb20cd0-fda0-4cf3-bdf2-46d18fab8279.jpg) ![1680858583027](https://user-images.githubusercontent.com/46481864/230583752-eccb840e-e1c1-4c4e-9c9c-73aa0f5e8567.jpg)

https://github.com/DerrickWang005/CRIS.pytorch/blob/master/tools/data_process.py

**Comment by euminds** [comment]
> > As the title, I didn't find dataset_process.py to handle the refcoco ! [1680858533476](https://user-images.githubusercontent.com/46481864/230583739-3bb20cd0-fda0-4cf3-bdf2-46d18fab8279.jpg) ![1680858583027](https://user-images.githubusercontent.com/46481864/230583752-eccb840e-e1c1-4c4e-9c9c-73aa0f5e8567.jpg)
> 
> https://github.com/DerrickWang005/CRIS.pytorch/blob/master/tools/data_process.py

Thanks

**Comment by helblazer811** [comment]
Thanks for pointing this out. I added the file to ```tools/```. I already had this data processed for another project so I forgot to move the processing file.
